{{- if .Values.ingress.webhook.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "byte-v-forge.componentFullname" (dict "root" . "component" "webhook") }}
  labels:
    {{- include "byte-v-forge.componentLabels" (dict "root" . "component" "webhook") | nindent 4 }}
  {{- with .Values.ingress.webhook.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.webhook.className }}
  ingressClassName: {{ .Values.ingress.webhook.className | quote }}
  {{- end }}
  {{- with .Values.ingress.webhook.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.webhook.hosts }}
    - http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "byte-v-forge.componentFullname" (dict "root" $ "component" (default "gpt-service" .component)) }}
                port:
                  name: {{ default "http-webhook" .portName | quote }}
          {{- end }}
      {{- with .host }}
      host: {{ . | quote }}
      {{- end }}
    {{- end }}
{{- end }}
