version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /images/go-builder
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /images/go-runtime
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /images/node-builder
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /images/browser-runtime
    schedule:
      interval: weekly
